# Generated by Django 5.2.7 on 2025-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_alter_task_categories_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('others', 'Others')], default='Inbox', max_length=20),
        ),
    ]
