# Generated by Django 5.2.7 on 2025-11-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_alter_task_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('others', 'Others')], default='Inbox', max_length=20),
        ),
    ]
