# Generated by Django 5.2.7 on 2025-11-18 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0006_alter_task_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focussession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='UserAuth.task'),
        ),
    ]
