# Generated by Django 5.2.7 on 2025-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0007_alter_focussession_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focussession',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
