# Generated by Django 5.2.7 on 2025-12-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0008_alter_focussession_start_time_alter_task_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FocusSession',
        ),
    ]
