# Generated by Django 5.2.7 on 2025-12-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0010_task_reminder_time_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
