# Generated by Django 5.2.7 on 2026-08-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0012_task_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alarm_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
